//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileCabinetApp.Resource {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileCabinetApp.Resource.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available commands: .
        /// </summary>
        internal static string AvailableCommandsMessage {
            get {
                return ResourceManager.GetString("AvailableCommandsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Record #{0} is created..
        /// </summary>
        internal static string CreateRecordMessage {
            get {
                return ResourceManager.GetString("CreateRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of birth: .
        /// </summary>
        internal static string DateOfBirthMessage {
            get {
                return ResourceManager.GetString("DateOfBirthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Evgeniy Slabko.
        /// </summary>
        internal static string DeveloperName {
            get {
                return ResourceManager.GetString("DeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The list is empty.
        /// </summary>
        internal static string EmptyListMessage {
            get {
                return ResourceManager.GetString("EmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exiting an application....
        /// </summary>
        internal static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First name: .
        /// </summary>
        internal static string FirstNameMessage {
            get {
                return ResourceManager.GetString("FirstNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \t{0}\t- {1}.
        /// </summary>
        internal static string HelpMessageTemplate {
            get {
                return ResourceManager.GetString("HelpMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your command, or enter &apos;help&apos; to get help..
        /// </summary>
        internal static string HintMessage {
            get {
                return ResourceManager.GetString("HintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Identification letter:.
        /// </summary>
        internal static string IdentificationLetterMessage {
            get {
                return ResourceManager.GetString("IdentificationLetterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Identification Number:.
        /// </summary>
        internal static string IdentificationNumberMessage {
            get {
                return ResourceManager.GetString("IdentificationNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid arguments.
        /// </summary>
        internal static string InvalidArgumentsMessage {
            get {
                return ResourceManager.GetString("InvalidArgumentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid date format.
        /// </summary>
        internal static string InvalidFormatMessage {
            get {
                return ResourceManager.GetString("InvalidFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last name: .
        /// </summary>
        internal static string LastNameMessage {
            get {
                return ResourceManager.GetString("LastNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overflow error.
        /// </summary>
        internal static string OverflowMessage {
            get {
                return ResourceManager.GetString("OverflowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Points for four tests:.
        /// </summary>
        internal static string PointsForFourTestsMessage {
            get {
                return ResourceManager.GetString("PointsForFourTestsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Records were not found.
        /// </summary>
        internal static string RecordFindMissMessage {
            get {
                return ResourceManager.GetString("RecordFindMissMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Record #{0} is updated..
        /// </summary>
        internal static string UppdateRecordMessage {
            get {
                return ResourceManager.GetString("UppdateRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Cabinet Application, developed by.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
